/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:ce6a6e5c-e67c-427f-b113-74cfc48a0618",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_fiXjNKr20",
    "aws_user_pools_web_client_id": "3lc1d9ajk4np83lhfjo5ddpc9n",
    "oauth": {}
};


export default awsmobile;
